version: '3.8'

services:
  notificaciones-db:
    image: mysql:8.0
    container_name: notificaciones-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quickbite_notificaciones
    ports:
      - "3307:3306"
    volumes:
      - notificaciones_data:/var/lib/mysql
    networks:
      - quickbite-network

  notificaciones-service:
    build: .
    container_name: notificaciones-service
    ports:
      - "8084:8084"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - notificaciones-db
    networks:
      - quickbite-network
    restart: unless-stopped

volumes:
  notificaciones_data:

networks:
  quickbite-network:
    external: true
